services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=host.docker.internal
      - DB_USER=root
      - DB_PASSWORD=gupta321@
      - DB_NAME=learn_mama
      - REDIS_URL=redis://default:G2HWyr7Ys7Kh0k8OxGDVA4g21pTGVGAR@redis-11737.c89.us-east-1-3.ec2.cloud.redislabs.com:11737
      - JWT_SECRET=your_jwt_secret_here
      - GOOGLE_CLIENT_ID=your_google_client_id
      - GOOGLE_CLIENT_SECRET=your_google_client_secret
      - RAZORPAY_KEY_ID=your_razorpay_key_id
      - RAZORPAY_KEY_SECRET=your_razorpay_key_secret
      - STRIPE_SECRET_KEY=your_stripe_secret_key
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
